### ISSUE TITLE
About restart control plane pod for containerd

### ISSUE THREAD

**Issue by whitebear009** [yuyicai/update-kube-cert#17]
I see that the bash script of containerd already contains the action of restarting the container. 
`
crictl ps | awk '/kube-'${item}'-/{print $(NF-1)}' | xargs -r -I '{}' crictl stopp {} >/dev/null 2>&1 || true 
`

Why does it need to be restarted manually as mentioned in the document for containerd?

(By the way, the script is very niubility... help me a lot)

**Comment by yuyicai** [comment]
Some people have reported that using crictl to restart the pod may not be effective. However, due to time constraints, I wasn't able to verify this myself. As a result, I've added a more robust restart method to the readme, following the official documentation, which involves removing the manifests to restart the pod. However, if your control-plane pod has already been successfully restarted after running the script, there's no need to remove the manifests for another restart.

**Comment by whitebear009** [comment]
I see, thanks a lot.
